name: benchmark_gnn
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch=2.5.1
  - torchvision=0.20.1
  - pytorch-cuda=12.4
  - numpy=1.26.0
  - matplotlib=3.8.0
  - tensorboard=2.14.0
  - tensorboardx=2.6.2.2
  - tqdm=4.66.1
  - networkx=3.2.1
  - scipy=1.11.3
  - h5py=3.10.0
  - pip=23.3.1
  - pip:
      - dgl==2.4.0+cu124 -f https://data.dgl.ai/wheels/cu124/repo.html
      - ogb==1.3.6
      - torchdata
